SoftMP3: int32 is not unsigned long...
Fixes the following error:
frameworks/av/media/libstagefright/codecs/mp3dec/
	SoftMP3.cpp:283:17
error: format specifies type 'unsigned long' but the argument has
	type 'OMX_U32' (aka 'unsigned int') [-Werror,-Wformat]
               outHeader->nAllocLen, mConfig->outputFrameSize);

Not sure how this derp fixes something in r46, but this fixes
compile for celox.  Need to test other platforms but should be OK.

Change-Id: I37c5d42162da7fff2b5d679d3b1bacc51dff6508